# Generated by Django 5.2.8 on 2025-11-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Montadora')),
                ('pais_origem', models.CharField(max_length=50, verbose_name='País de Origem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='montadoras/', verbose_name='Logo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Montadora',
                'verbose_name_plural': 'Montadoras',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VeiculoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano_inicial', models.IntegerField(verbose_name='Ano Inicial')),
                ('ano_final', models.IntegerField(blank=True, help_text='Deixe em branco se ainda está em produção', null=True, verbose_name='Ano Final')),
                ('tipo', models.CharField(choices=[('HATCH', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('PICKUP', 'Picape'), ('VAN', 'Van/Utilitário'), ('WAGON', 'Station Wagon'), ('SPORT', 'Esportivo')], default='HATCH', max_length=10, verbose_name='Tipo')),
                ('motorizacoes', models.CharField(help_text='Ex: 1.0, 1.4, 1.6, 2.0', max_length=200, verbose_name='Motorizações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('popular', models.BooleanField(default=False, help_text='Marca para destacar modelos mais vendidos', verbose_name='Modelo Popular')),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='estoque.montadora', verbose_name='Montadora')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'ordering': ['montadora__nome', 'nome', '-ano_inicial'],
                'indexes': [models.Index(fields=['montadora', 'nome'], name='estoque_vei_montado_da62a0_idx'), models.Index(fields=['popular'], name='estoque_vei_popular_7d5642_idx')],
                'unique_together': {('montadora', 'nome', 'ano_inicial')},
            },
        ),
    ]
