# Generated by Django 5.2.8 on 2025-11-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_montadora_veiculomodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Versão')),
                ('ano_inicial', models.IntegerField(verbose_name='Ano Inicial')),
                ('ano_final', models.IntegerField(blank=True, null=True, verbose_name='Ano Final')),
                ('motorizacoes', models.CharField(max_length=200, verbose_name='Motorizações')),
                ('codigo_fipe', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código FIPE')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Versão do Veículo',
                'verbose_name_plural': 'Versões dos Veículos',
                'ordering': ['modelo__montadora__nome', 'modelo__nome', '-ano_inicial', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='veiculomodelo',
            options={'ordering': ['montadora__nome', 'nome'], 'verbose_name': 'Modelo de Veículo', 'verbose_name_plural': 'Modelos de Veículos'},
        ),
        migrations.RemoveIndex(
            model_name='veiculomodelo',
            name='estoque_vei_montado_da62a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='veiculomodelo',
            name='estoque_vei_popular_7d5642_idx',
        ),
        migrations.AlterUniqueTogether(
            name='veiculomodelo',
            unique_together={('montadora', 'nome')},
        ),
        migrations.AddField(
            model_name='veiculomodelo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='veiculomodelo',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Modelo Popular'),
        ),
        migrations.AlterField(
            model_name='veiculomodelo',
            name='tipo',
            field=models.CharField(choices=[('HATCH', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV/Crossover'), ('PICKUP', 'Picape'), ('VAN', 'Van/Utilitário'), ('WAGON', 'Station Wagon'), ('SPORT', 'Esportivo')], default='HATCH', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='veiculoversao',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='estoque.veiculomodelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='versoes_compativeis',
            field=models.ManyToManyField(blank=True, help_text='Selecione todas as versões de veículos compatíveis', related_name='produtos', to='estoque.veiculoversao', verbose_name='Versões Compatíveis'),
        ),
        migrations.RemoveField(
            model_name='veiculomodelo',
            name='ano_final',
        ),
        migrations.RemoveField(
            model_name='veiculomodelo',
            name='ano_inicial',
        ),
        migrations.RemoveField(
            model_name='veiculomodelo',
            name='motorizacoes',
        ),
        migrations.AlterUniqueTogether(
            name='veiculoversao',
            unique_together={('modelo', 'nome', 'ano_inicial')},
        ),
    ]
