# Generated by Django 5.2.8 on 2025-11-24 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_veiculoversao_alter_veiculomodelo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_venda_debito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Venda - Débito'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='estoque.categoria', verbose_name='Categoria'),
        ),
    ]
