# Generated by Django 5.2.8 on 2025-11-24 21:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_preco_venda_debito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='aplicacoes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_ultima_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_ultima_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='localizacao_completa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='margem_lucro_credito',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='margem_lucro_dinheiro',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_reposicao',
            field=models.IntegerField(blank=True, default=0, verbose_name='Qtd Sugerida para Reposição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aplicacao_generica',
            field=models.TextField(blank=True, default='', help_text='Texto livre para descrever compatibilidade', null=True, verbose_name='Aplicação Genérica'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Produto Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, verbose_name='Comprimento (cm)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Em Destaque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='divisao_prateleira',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Divisão/Gaveta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(blank=True, default=0, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_maximo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Estoque Máximo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_reservado',
            field=models.IntegerField(blank=True, default=0, verbose_name='Estoque Reservado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='garantia_meses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Garantia (meses)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, verbose_name='Largura (cm)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.CharField(blank=True, choices=[('1', 'Loja 1'), ('2', 'Loja 2')], default='1', max_length=1, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prateleira',
            field=models.CharField(blank=True, choices=[('', 'Não definida'), ('A', 'Prateleira A'), ('B', 'Prateleira B'), ('C', 'Prateleira C'), ('D', 'Prateleira D'), ('E', 'Prateleira E'), ('F', 'Prateleira F'), ('G', 'Prateleira G'), ('H', 'Prateleira H')], default='', max_length=1, null=True, verbose_name='Prateleira'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_atacado',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço Atacado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço no Crédito'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda_debito',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço no Débito'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda_dinheiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Preço à Vista (Dinheiro)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima_atacado',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Qtd Mínima p/ Atacado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('CJ', 'Conjunto'), ('KIT', 'Kit'), ('PAR', 'Par'), ('JG', 'Jogo'), ('CX', 'Caixa'), ('MT', 'Metro'), ('LT', 'Litro'), ('KG', 'Quilograma')], default='UN', max_length=5, verbose_name='Unidade de Medida'),
        ),
    ]
