# Generated by Django 5.2.8 on 2025-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_adicionar_quantidade_reposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aplicar_imposto_4',
            field=models.BooleanField(default=False, help_text='Marca se este produto deve ter 4% de imposto incluído no preço final', verbose_name='Aplicar Imposto 4% (Simples Nacional)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_10x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 10x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_11x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 11x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_12x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 12x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_2x',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço customizado para 2 parcelas', max_digits=10, null=True, verbose_name='Preço Crédito 2x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_3x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 3x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_4x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 4x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_5x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 5x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_6x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 6x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_7x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 7x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_8x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 8x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_credito_9x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Crédito 9x'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_customizado_cartao',
            field=models.BooleanField(default=False, help_text='Se marcado, você define preços manualmente por parcela. Se desmarcado, usa taxa automática.', verbose_name='Usar Preços Customizados no Cartão'),
        ),
    ]
