# Generated by Django 5.2.8 on 2025-11-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_aplicar_imposto_4_produto_preco_credito_10x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='estoque.subcategoria', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['subcategoria__categoria__nome', 'subcategoria__nome', 'nome'],
                'unique_together': {('subcategoria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.grupo', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='estoque.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
                'ordering': ['grupo__subcategoria__categoria__nome', 'grupo__subcategoria__nome', 'grupo__nome', 'nome'],
                'unique_together': {('grupo', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.subgrupo', verbose_name='Subgrupo'),
        ),
    ]
