# Generated by Django 5.2.8 on 2025-11-30 14:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_grupo_produto_grupo_subgrupo_produto_subgrupo'),
        ('vendas', '0002_orcamento_itemorcamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmperagemBateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperagem', models.CharField(help_text='Ex: 40Ah, 60Ah, 90Ah Caixa Alta', max_length=20, unique=True, verbose_name='Amperagem')),
                ('nome_tecnico', models.CharField(blank=True, help_text='Ex: NS40, 22F, 30H', max_length=50, null=True, verbose_name='Nome Técnico')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso aproximado do casco em kg', max_digits=5, verbose_name='Peso (kg)')),
                ('valor_casco_troca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do casco na troca - desconto/acréscimo para o cliente', max_digits=10, verbose_name='Valor Casco (Troca)')),
                ('valor_casco_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor que você paga para comprar casco avulso', max_digits=10, verbose_name='Valor Casco (Compra)')),
                ('aplicacao', models.CharField(blank=True, help_text='Ex: Honda City, Honda Fit, Veículos compactos', max_length=200, null=True, verbose_name='Aplicação Comum')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Amperagem de Bateria',
                'verbose_name_plural': 'Amperagens de Bateria',
                'ordering': ['ordem', 'amperagem'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='amperagem_bateria',
            field=models.ForeignKey(blank=True, help_text='Preencher apenas se o produto for uma bateria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.amperagembateria', verbose_name='Amperagem (Bateria)'),
        ),
        migrations.CreateModel(
            name='EstoqueCasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, help_text='Total de cascos (baterias novas + cascos avulsos)', verbose_name='Quantidade de Cascos')),
                ('amperagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_casco', to='estoque.amperagembateria', verbose_name='Amperagem')),
            ],
            options={
                'verbose_name': 'Estoque de Casco',
                'verbose_name_plural': 'Estoque de Cascos',
                'ordering': ['amperagem__ordem', 'amperagem__amperagem'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaBateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_trouxe_casco', models.BooleanField(default=True, verbose_name='Cliente Trouxe Casco')),
                ('valor_casco_vendido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do casco da bateria vendida', max_digits=10, verbose_name='Valor Casco Vendido')),
                ('valor_casco_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do casco que o cliente trouxe', max_digits=10, verbose_name='Valor Casco Recebido')),
                ('diferenca_casco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positivo = acréscimo, Negativo = desconto', max_digits=10, verbose_name='Diferença de Casco')),
                ('amperagem_casco_recebido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascos_recebidos', to='estoque.amperagembateria', verbose_name='Amperagem do Casco Recebido')),
                ('amperagem_vendida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_bateria', to='estoque.amperagembateria', verbose_name='Amperagem Vendida')),
                ('item_venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_bateria', to='vendas.itemvenda', verbose_name='Item da Venda')),
            ],
            options={
                'verbose_name': 'Info Bateria da Venda',
                'verbose_name_plural': 'Info Baterias das Vendas',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('motivo', models.CharField(choices=[('VENDA_COM_TROCA', 'Venda com troca de casco'), ('VENDA_SEM_TROCA', 'Venda sem troca de casco'), ('COMPRA_BATERIA', 'Compra de bateria nova'), ('COMPRA_CASCO', 'Compra de casco avulso'), ('VENDA_CASCO', 'Venda de casco para reciclagem'), ('CASCO_EXTRA', 'Casco extra do cliente'), ('AJUSTE', 'Ajuste de estoque'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Motivo')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('amperagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.amperagembateria', verbose_name='Amperagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_casco', to='vendas.venda', verbose_name='Venda Relacionada')),
            ],
            options={
                'verbose_name': 'Movimentação de Casco',
                'verbose_name_plural': 'Movimentações de Casco',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
