# Generated by Django 5.0.14 on 2025-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0008_amperagembateria_produto_amperagem_bateria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="tem_st",
            field=models.BooleanField(
                default=False,
                help_text="Marque se este produto tem ICMS-ST (maioria das autopeças tem)",
                verbose_name="Tem Substituição Tributária",
            ),
        ),
    ]
