# Generated by Django 5.2.8 on 2025-11-23 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0002_montadora_veiculomodelo'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Orçamento')),
                ('data_orcamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Orçamento')),
                ('data_validade', models.DateField(verbose_name='Validade')),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa')),
                ('veiculo_ano', models.IntegerField(blank=True, null=True, verbose_name='Ano do Veículo')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENVIADO', 'Enviado ao Cliente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONVERTIDO', 'Convertido em Venda'), ('EXPIRADO', 'Expirado')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro/PIX'), ('DEBITO', 'Cartão Débito'), ('CREDITO', 'Cartão Crédito'), ('ATACADO', 'Atacado')], default='DINHEIRO', max_length=10, verbose_name='Forma de Pagamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_conversao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conversão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente', verbose_name='Cliente')),
                ('veiculo_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.veiculomodelo', verbose_name='Modelo do Veículo')),
                ('venda_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda', verbose_name='Venda Gerada')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_orcamento'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto no Item')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('estoque_disponivel', models.IntegerField(default=0, editable=False, verbose_name='Estoque Disponível')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens do Orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['numero'], name='vendas_orca_numero_8d28b8_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status'], name='vendas_orca_status_f1be28_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['cliente'], name='vendas_orca_cliente_a0d167_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['-data_orcamento'], name='vendas_orca_data_or_b0caa9_idx'),
        ),
    ]
