# Generated by Django 5.0.14 on 2025-12-20 20:40

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("estoque", "0009_produto_tem_st"),
        (
            "financeiro",
            "0004_contafinanceira_resumodiariovendas_fechamentocaixa_and_more",
        ),
        ("vendas", "0002_orcamento_itemorcamento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CFOP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="Código CFOP"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "aplicacao",
                    models.TextField(blank=True, null=True, verbose_name="Aplicação"),
                ),
                (
                    "entrada_saida",
                    models.CharField(
                        choices=[("E", "Entrada"), ("S", "Saída")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CFOP",
                "verbose_name_plural": "CFOPs",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=200, verbose_name="Nome Fantasia"),
                ),
                ("cnpj", models.CharField(max_length=18, verbose_name="CNPJ")),
                (
                    "inscricao_estadual",
                    models.CharField(max_length=20, verbose_name="Inscrição Estadual"),
                ),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Inscrição Municipal",
                    ),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(max_length=200, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "codigo_municipio",
                    models.CharField(
                        max_length=7, verbose_name="Código IBGE Município"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email para envio de notas"
                    ),
                ),
                (
                    "regime_tributario",
                    models.CharField(
                        choices=[
                            ("1", "Simples Nacional"),
                            ("2", "Simples Nacional - Excesso"),
                            ("3", "Regime Normal"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Regime Tributário",
                    ),
                ),
                (
                    "ambiente",
                    models.CharField(
                        choices=[("1", "Produção"), ("2", "Homologação (Teste)")],
                        default="2",
                        max_length=1,
                        verbose_name="Ambiente",
                    ),
                ),
                (
                    "certificado_arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificados/",
                        verbose_name="Certificado Digital A1 (.pfx)",
                    ),
                ),
                (
                    "certificado_senha",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Senha do Certificado",
                    ),
                ),
                (
                    "certificado_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validade do Certificado"
                    ),
                ),
                (
                    "webmania_consumer_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Consumer Key",
                    ),
                ),
                (
                    "webmania_consumer_secret",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Consumer Secret",
                    ),
                ),
                (
                    "webmania_access_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Access Token",
                    ),
                ),
                (
                    "webmania_access_token_secret",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Access Token Secret",
                    ),
                ),
                (
                    "csc_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="ID do CSC (NFC-e)",
                    ),
                ),
                (
                    "csc_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Token CSC (NFC-e)",
                    ),
                ),
                (
                    "serie_nfe",
                    models.IntegerField(default=1, verbose_name="Série NF-e"),
                ),
                (
                    "serie_nfce",
                    models.IntegerField(default=1, verbose_name="Série NFC-e"),
                ),
                (
                    "proximo_numero_nfe",
                    models.IntegerField(default=1, verbose_name="Próximo Número NF-e"),
                ),
                (
                    "proximo_numero_nfce",
                    models.IntegerField(default=1, verbose_name="Próximo Número NFC-e"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração Fiscal",
                "verbose_name_plural": "Configurações Fiscais",
            },
        ),
        migrations.CreateModel(
            name="NCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Código NCM"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                (
                    "aliquota_ipi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota IPI (%)",
                    ),
                ),
                (
                    "tem_substituicao_tributaria",
                    models.BooleanField(default=False, verbose_name="Tem ST?"),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "NCM",
                "verbose_name_plural": "NCMs",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Boleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nosso_numero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Nosso Número",
                    ),
                ),
                (
                    "linha_digitavel",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Linha Digitável",
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código de Barras",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        choices=[
                            ("001", "Banco do Brasil"),
                            ("033", "Santander"),
                            ("104", "Caixa Econômica"),
                            ("237", "Bradesco"),
                            ("341", "Itaú"),
                            ("077", "Banco Inter"),
                            ("756", "Sicoob"),
                            ("748", "Sicredi"),
                            ("asaas", "Asaas"),
                            ("paghiper", "PagHiper"),
                        ],
                        max_length=10,
                        verbose_name="Banco",
                    ),
                ),
                (
                    "pagador_cpf_cnpj",
                    models.CharField(max_length=18, verbose_name="CPF/CNPJ"),
                ),
                ("pagador_nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "pagador_endereco",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data Emissão"
                    ),
                ),
                ("data_vencimento", models.DateField(verbose_name="Data Vencimento")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Pagamento"
                    ),
                ),
                (
                    "juros_ao_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Juros ao Dia (%)",
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Multa (%)",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "instrucao_1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Instrução 1",
                    ),
                ),
                (
                    "instrucao_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Instrução 2",
                    ),
                ),
                (
                    "instrucao_3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Instrução 3",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("REGISTRADO", "Registrado"),
                            ("PAGO", "Pago"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                            ("PROTESTADO", "Protestado"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "id_externo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ID na API"
                    ),
                ),
                (
                    "url_boleto",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL do Boleto"
                    ),
                ),
                (
                    "pdf_boleto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="boletos/%Y/%m/",
                        verbose_name="PDF do Boleto",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "conta_receber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boletos",
                        to="financeiro.contareceber",
                        verbose_name="Conta a Receber",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto",
                "verbose_name_plural": "Boletos",
                "ordering": ["-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="InutilizacaoNumeracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        choices=[("55", "NF-e"), ("65", "NFC-e")],
                        max_length=2,
                        verbose_name="Modelo",
                    ),
                ),
                ("serie", models.IntegerField(verbose_name="Série")),
                ("numero_inicial", models.IntegerField(verbose_name="Número Inicial")),
                ("numero_final", models.IntegerField(verbose_name="Número Final")),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Mínimo 15 caracteres", verbose_name="Justificativa"
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Protocolo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDENTE", max_length=15, verbose_name="Status"
                    ),
                ),
                ("data_inutilizacao", models.DateTimeField(blank=True, null=True)),
                ("xml_envio", models.TextField(blank=True, null=True)),
                ("xml_retorno", models.TextField(blank=True, null=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inutilização de Numeração",
                "verbose_name_plural": "Inutilizações de Numeração",
            },
        ),
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "modelo",
                    models.CharField(
                        choices=[
                            ("55", "NF-e (Modelo 55)"),
                            ("65", "NFC-e (Modelo 65)"),
                        ],
                        default="65",
                        max_length=2,
                        verbose_name="Modelo",
                    ),
                ),
                ("serie", models.IntegerField(default=1, verbose_name="Série")),
                ("numero", models.IntegerField(verbose_name="Número")),
                (
                    "chave_acesso",
                    models.CharField(
                        blank=True,
                        max_length=44,
                        null=True,
                        verbose_name="Chave de Acesso",
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Protocolo de Autorização",
                    ),
                ),
                (
                    "data_autorizacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Autorização"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("AUTORIZADA", "Autorizada"),
                            ("REJEITADA", "Rejeitada"),
                            ("CANCELADA", "Cancelada"),
                            ("DENEGADA", "Denegada"),
                            ("INUTILIZADA", "Inutilizada"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "motivo_rejeicao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo Rejeição"
                    ),
                ),
                (
                    "codigo_status_sefaz",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código Status SEFAZ",
                    ),
                ),
                (
                    "natureza_operacao",
                    models.CharField(
                        default="VENDA DE MERCADORIA",
                        max_length=100,
                        verbose_name="Natureza da Operação",
                    ),
                ),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[("0", "Entrada"), ("1", "Saída")],
                        default="1",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("1", "NF-e Normal"),
                            ("2", "NF-e Complementar"),
                            ("3", "NF-e de Ajuste"),
                            ("4", "Devolução de Mercadoria"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Finalidade",
                    ),
                ),
                (
                    "presenca",
                    models.CharField(
                        choices=[
                            ("0", "Não se aplica"),
                            ("1", "Operação presencial"),
                            ("2", "Operação não presencial, Internet"),
                            ("3", "Operação não presencial, Teleatendimento"),
                            ("4", "NFC-e em operação com entrega a domicílio"),
                            ("5", "Operação presencial, fora do estabelecimento"),
                            ("9", "Operação não presencial, outros"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Presença do Comprador",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data Emissão"
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Saída"
                    ),
                ),
                (
                    "dest_cpf_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        verbose_name="CPF/CNPJ Destinatário",
                    ),
                ),
                (
                    "dest_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome/Razão Social",
                    ),
                ),
                (
                    "dest_ie",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Inscrição Estadual",
                    ),
                ),
                (
                    "dest_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "dest_telefone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "dest_cep",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "dest_logradouro",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Logradouro"
                    ),
                ),
                (
                    "dest_numero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "dest_complemento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "dest_bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "dest_cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "dest_uf",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "dest_codigo_municipio",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Código Município",
                    ),
                ),
                (
                    "valor_produtos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor dos Produtos",
                    ),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor do Frete",
                    ),
                ),
                (
                    "valor_seguro",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor do Seguro",
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor do Desconto",
                    ),
                ),
                (
                    "valor_outras_despesas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Outras Despesas",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor Total da Nota",
                    ),
                ),
                (
                    "base_calculo_icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Base Cálculo ICMS",
                    ),
                ),
                (
                    "valor_icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor ICMS",
                    ),
                ),
                (
                    "valor_icms_st",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor ICMS ST",
                    ),
                ),
                (
                    "valor_ipi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor IPI",
                    ),
                ),
                (
                    "valor_pis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor PIS",
                    ),
                ),
                (
                    "valor_cofins",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor COFINS",
                    ),
                ),
                (
                    "informacoes_complementares",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Complementares"
                    ),
                ),
                (
                    "informacoes_fisco",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações ao Fisco"
                    ),
                ),
                (
                    "xml_envio",
                    models.TextField(
                        blank=True, null=True, verbose_name="XML de Envio"
                    ),
                ),
                (
                    "xml_retorno",
                    models.TextField(
                        blank=True, null=True, verbose_name="XML de Retorno"
                    ),
                ),
                (
                    "xml_autorizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="XML Autorizado"
                    ),
                ),
                (
                    "pdf_danfe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notas_fiscais/danfe/%Y/%m/",
                        verbose_name="DANFE (PDF)",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_fiscais",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_fiscais",
                        to="vendas.venda",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Fiscal",
                "verbose_name_plural": "Notas Fiscais",
                "ordering": ["-data_emissao"],
                "unique_together": {("modelo", "serie", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ItemNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_item", models.IntegerField(verbose_name="Nº Item")),
                ("codigo", models.CharField(max_length=60, verbose_name="Código")),
                (
                    "descricao",
                    models.CharField(max_length=120, verbose_name="Descrição"),
                ),
                ("ncm", models.CharField(max_length=8, verbose_name="NCM")),
                ("cfop", models.CharField(max_length=4, verbose_name="CFOP")),
                (
                    "unidade",
                    models.CharField(
                        default="UN", max_length=6, verbose_name="Unidade"
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor Total"
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("0", "Nacional"),
                            ("1", "Estrangeira - Importação direta"),
                            ("2", "Estrangeira - Adquirida no mercado interno"),
                            ("3", "Nacional - Conteúdo de importação > 40%"),
                            ("4", "Nacional - Produção conforme processos básicos"),
                            ("5", "Nacional - Conteúdo de importação <= 40%"),
                            (
                                "6",
                                "Estrangeira - Importação direta, sem similar nacional",
                            ),
                            (
                                "7",
                                "Estrangeira - Adquirida no mercado interno, sem similar nacional",
                            ),
                            ("8", "Nacional - Conteúdo de importação > 70%"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "csosn",
                    models.CharField(
                        choices=[
                            ("101", "101 - Tributada com permissão de crédito"),
                            ("102", "102 - Tributada sem permissão de crédito"),
                            (
                                "103",
                                "103 - Isenção do ICMS para faixa de receita bruta",
                            ),
                            (
                                "201",
                                "201 - Tributada com permissão de crédito e com cobrança de ST",
                            ),
                            (
                                "202",
                                "202 - Tributada sem permissão de crédito e com cobrança de ST",
                            ),
                            (
                                "203",
                                "203 - Isenção do ICMS para faixa de receita bruta e com cobrança de ST",
                            ),
                            ("300", "300 - Imune"),
                            ("400", "400 - Não tributada"),
                            ("500", "500 - ICMS cobrado anteriormente por ST"),
                            ("900", "900 - Outros"),
                        ],
                        default="102",
                        max_length=3,
                        verbose_name="CSOSN",
                    ),
                ),
                (
                    "base_calculo_icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Base Cálculo ICMS",
                    ),
                ),
                (
                    "aliquota_icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota ICMS",
                    ),
                ),
                (
                    "valor_icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor ICMS",
                    ),
                ),
                (
                    "base_calculo_icms_st",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Base Cálculo ICMS ST",
                    ),
                ),
                (
                    "aliquota_icms_st",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota ICMS ST",
                    ),
                ),
                (
                    "valor_icms_st",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor ICMS ST",
                    ),
                ),
                (
                    "aliquota_pis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota PIS",
                    ),
                ),
                (
                    "valor_pis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor PIS",
                    ),
                ),
                (
                    "aliquota_cofins",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota COFINS",
                    ),
                ),
                (
                    "valor_cofins",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor COFINS",
                    ),
                ),
                (
                    "aliquota_ipi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Alíquota IPI",
                    ),
                ),
                (
                    "valor_ipi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valor IPI",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="fiscal.notafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Nota Fiscal",
                "verbose_name_plural": "Itens da Nota Fiscal",
                "ordering": ["numero_item"],
            },
        ),
        migrations.CreateModel(
            name="EventoNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CANCELAMENTO", "Cancelamento"),
                            ("CARTA_CORRECAO", "Carta de Correção"),
                            ("CIENCIA", "Ciência da Operação"),
                            ("CONFIRMACAO", "Confirmação da Operação"),
                            ("DESCONHECIMENTO", "Desconhecimento da Operação"),
                            ("NAO_REALIZADA", "Operação não Realizada"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                ("sequencia", models.IntegerField(default=1, verbose_name="Sequência")),
                (
                    "protocolo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Protocolo"
                    ),
                ),
                (
                    "data_evento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data do Evento"
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "correcao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto da Correção"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDENTE", max_length=15, verbose_name="Status"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo/Retorno"
                    ),
                ),
                (
                    "xml_evento",
                    models.TextField(
                        blank=True, null=True, verbose_name="XML do Evento"
                    ),
                ),
                (
                    "xml_retorno",
                    models.TextField(
                        blank=True, null=True, verbose_name="XML de Retorno"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="fiscal.notafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Nota Fiscal",
                "verbose_name_plural": "Eventos da Nota Fiscal",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="DuplicataNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=60, verbose_name="Número da Duplicata"),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicatas",
                        to="fiscal.boleto",
                        verbose_name="Boleto",
                    ),
                ),
                (
                    "conta_receber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicatas_nf",
                        to="financeiro.contareceber",
                        verbose_name="Conta a Receber",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicatas",
                        to="fiscal.notafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duplicata",
                "verbose_name_plural": "Duplicatas",
                "ordering": ["data_vencimento"],
            },
        ),
        migrations.AddField(
            model_name="boleto",
            name="nota_fiscal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boletos",
                to="fiscal.notafiscal",
                verbose_name="Nota Fiscal",
            ),
        ),
        migrations.CreateModel(
            name="PagamentoNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("01", "Dinheiro"),
                            ("02", "Cheque"),
                            ("03", "Cartão de Crédito"),
                            ("04", "Cartão de Débito"),
                            ("05", "Crédito Loja"),
                            ("10", "Vale Alimentação"),
                            ("11", "Vale Refeição"),
                            ("12", "Vale Presente"),
                            ("13", "Vale Combustível"),
                            ("15", "Boleto Bancário"),
                            ("16", "Depósito Bancário"),
                            ("17", "PIX"),
                            ("18", "Transferência"),
                            ("19", "Programa de Fidelidade"),
                            ("90", "Sem Pagamento"),
                            ("99", "Outros"),
                        ],
                        max_length=2,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "bandeira",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Visa"),
                            ("02", "Mastercard"),
                            ("03", "American Express"),
                            ("04", "Sorocred"),
                            ("05", "Diners Club"),
                            ("06", "Elo"),
                            ("07", "Hipercard"),
                            ("08", "Aura"),
                            ("09", "Cabal"),
                            ("99", "Outros"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Bandeira",
                    ),
                ),
                (
                    "autorizacao",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código Autorização",
                    ),
                ),
                (
                    "cnpj_credenciadora",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        verbose_name="CNPJ Credenciadora",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="fiscal.notafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento da Nota Fiscal",
                "verbose_name_plural": "Pagamentos da Nota Fiscal",
            },
        ),
    ]
