# Generated by Django 5.2.8 on 2025-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('PIX', 'PIX')], max_length=10, verbose_name='Tipo')),
                ('parcelas', models.IntegerField(default=1, help_text='1 para débito, PIX ou crédito à vista', verbose_name='Parcelas')),
                ('taxa_percentual', models.DecimalField(decimal_places=2, help_text='Taxa cobrada pela operadora', max_digits=5, verbose_name='Taxa (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Taxa de Cartão',
                'verbose_name_plural': 'Taxas de Cartão',
                'ordering': ['tipo', 'parcelas'],
                'unique_together': {('tipo', 'parcelas')},
            },
        ),
    ]
