# Generated by Django 5.2.8 on 2025-11-25 12:38

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10, verbose_name='Tipo')),
                ('icone', models.CharField(default='bi-folder', help_text='Classe do ícone Bootstrap (ex: bi-house)', max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor em hexadecimal', max_length=20, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Simples Nacional', max_length=100, verbose_name='Nome')),
                ('aliquota', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5, verbose_name='Alíquota (%)')),
                ('dia_vencimento', models.IntegerField(default=20, help_text='Dia do mês seguinte para pagamento', verbose_name='Dia de Vencimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Tributo',
                'verbose_name_plural': 'Configurações de Tributos',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('icone', models.CharField(default='bi-wallet', max_length=50, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('numero_parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('data_primeira_parcela', models.DateField(verbose_name='Data da Primeira Parcela')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesa', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Compra Parcelada',
                'verbose_name_plural': 'Compras Parceladas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dia_vencimento', models.IntegerField(help_text='Dia do mês para vencimento', verbose_name='Dia de Vencimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco para despesa sem prazo', null=True, verbose_name='Data de Término')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesa', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
                'ordering': ['dia_vencimento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='FaturamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('valor_faturamento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Faturamento')),
                ('valor_tributo', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor do Tributo')),
                ('aliquota_aplicada', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Alíquota Aplicada (%)')),
                ('data_vencimento_tributo', models.DateField(verbose_name='Data Vencimento Tributo')),
                ('tributo_gerado', models.BooleanField(default=False, verbose_name='Tributo Gerado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('calculado_automaticamente', models.BooleanField(default=True, verbose_name='Calculado Automaticamente')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faturamento Mensal',
                'verbose_name_plural': 'Faturamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável'), ('TRIBUTO', 'Tributo'), ('PARCELADO', 'Parcelado')], default='VARIAVEL', max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('parcela_atual', models.IntegerField(default=1, verbose_name='Parcela Atual')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesa', verbose_name='Categoria')),
                ('compra_parcelada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.compraparcelada')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('despesa_fixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesafixa', verbose_name='Despesa Fixa Origem')),
                ('faturamento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tributos', to='financeiro.faturamentomensal')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.formapagamento', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento', 'descricao'],
            },
        ),
    ]
