# Generated by Django 5.2.8 on 2025-11-27 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0006_produto_aplicar_imposto_4_produto_preco_credito_10x_and_more'),
        ('financeiro', '0002_categoriadespesa_configuracaotributo_formapagamento_and_more'),
        ('vendas', '0002_orcamento_itemorcamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('VENDA', 'Venda'), ('SERVICO', 'Serviço'), ('OUTROS', 'Outros')], default='VENDA', max_length=10, verbose_name='Tipo')),
                ('icone', models.CharField(default='bi-cash', help_text='Classe do ícone Bootstrap (ex: bi-cash-stack)', max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#22c55e', help_text='Cor em hexadecimal', max_length=20, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Receita',
                'verbose_name_plural': 'Categorias de Receitas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juros_padrao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Padrão ao Dia (%)')),
                ('multa_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Multa Padrão por Atraso (%)')),
                ('dias_tolerancia', models.IntegerField(default=0, verbose_name='Dias de Tolerância')),
                ('dias_alerta_vencimento', models.IntegerField(default=7, verbose_name='Dias para Alerta de Vencimento')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.AddField(
            model_name='compraparcelada',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_parceladas', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='compraparcelada',
            name='intervalo_dias',
            field=models.IntegerField(default=30, help_text='Usado quando intervalo é Personalizado', verbose_name='Dias entre Parcelas'),
        ),
        migrations.AddField(
            model_name='compraparcelada',
            name='intervalo_tipo',
            field=models.CharField(choices=[('MENSAL', 'Mensal (30 dias)'), ('QUINZENAL', 'Quinzenal (15 dias)'), ('SEMANAL', 'Semanal (7 dias)'), ('PERSONALIZADO', 'Personalizado')], default='MENSAL', max_length=15, verbose_name='Intervalo'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/NF'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='despesafixa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_fixas', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('AMBOS', 'Despesa e Receita'), ('DESPESA', 'Apenas Despesa'), ('RECEITA', 'Apenas Receita')], default='AMBOS', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='VendaParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('numero_parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('data_primeira_parcela', models.DateField(verbose_name='Data da Primeira Parcela')),
                ('intervalo_tipo', models.CharField(choices=[('MENSAL', 'Mensal (30 dias)'), ('QUINZENAL', 'Quinzenal (15 dias)'), ('SEMANAL', 'Semanal (7 dias)'), ('DECENAL', 'A cada 10 dias'), ('PERSONALIZADO', 'Personalizado')], default='MENSAL', max_length=15, verbose_name='Intervalo')),
                ('intervalo_dias', models.IntegerField(default=30, help_text='Usado quando intervalo é Personalizado', verbose_name='Dias entre Parcelas')),
                ('forma_cobranca', models.CharField(choices=[('BOLETO', 'Boleto'), ('FIADO', 'Fiado'), ('CARNE', 'Carnê'), ('CHEQUE', 'Cheque')], default='FIADO', max_length=15, verbose_name='Forma de Cobrança')),
                ('aplica_juros', models.BooleanField(default=False, verbose_name='Aplica Juros?')),
                ('percentual_juros_dia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Juros ao Dia')),
                ('aplica_multa', models.BooleanField(default=False, verbose_name='Aplica Multa?')),
                ('percentual_multa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Multa por Atraso')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriareceita', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_parceladas', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamentos', to='vendas.venda', verbose_name='Venda Origem')),
            ],
            options={
                'verbose_name': 'Venda Parcelada',
                'verbose_name_plural': 'Vendas Parceladas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('VENDA', 'Venda'), ('SERVICO', 'Serviço/OS'), ('AVULSO', 'Receita Avulsa'), ('PARCELADO', 'Parcelado')], default='VENDA', max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('forma_cobranca', models.CharField(choices=[('BOLETO', 'Boleto'), ('FIADO', 'Fiado'), ('CARTAO', 'Cartão'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito/Transferência')], default='FIADO', max_length=15, verbose_name='Forma de Cobrança')),
                ('parcela_atual', models.IntegerField(default=1, verbose_name='Parcela Atual')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('aplica_juros', models.BooleanField(default=False, verbose_name='Aplica Juros?')),
                ('percentual_juros_dia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Juros ao Dia')),
                ('aplica_multa', models.BooleanField(default=False, verbose_name='Aplica Multa?')),
                ('percentual_multa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Multa por Atraso')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Juros Calculado')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Multa Calculado')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Recebido')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/NF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes_receitas/%Y/%m/', verbose_name='Comprovante')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriareceita', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='clientes.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.formapagamento', verbose_name='Forma de Pagamento (recebido)')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_receber', to='vendas.ordemservico', verbose_name='Ordem de Serviço')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_receber', to='vendas.venda', verbose_name='Venda')),
                ('venda_parcelada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.vendaparcelada')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento', 'descricao'],
            },
        ),
    ]
