# Generated by Django 5.2.9 on 2025-12-16 21:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0008_amperagembateria_produto_amperagem_bateria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(default=1, verbose_name='Nº Item')),
                ('codigo_produto_fornecedor', models.CharField(help_text='Código do produto no fornecedor', max_length=60, verbose_name='Código do Fornecedor')),
                ('codigo_barras_nf', models.CharField(blank=True, default='', help_text='EAN/GTIN da nota fiscal', max_length=14, verbose_name='Código de Barras (NF)')),
                ('descricao_nf', models.CharField(max_length=120, verbose_name='Descrição na NF')),
                ('ncm', models.CharField(blank=True, default='', max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, default='', max_length=7, verbose_name='CEST')),
                ('cfop', models.CharField(blank=True, default='', max_length=4, verbose_name='CFOP')),
                ('unidade', models.CharField(default='UN', max_length=6, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade NF')),
                ('quantidade_conferida', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Qtd Conferida')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IPI')),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ICMS ST')),
                ('valor_custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Custo com rateio de frete/impostos', max_digits=12, verbose_name='Custo Unitário')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido')),
                ('divergencia', models.BooleanField(default=False, help_text='Quantidade conferida difere da NF', verbose_name='Com Divergência')),
                ('observacao', models.CharField(blank=True, default='', max_length=200, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, help_text='Produto do sistema vinculado a este item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='estoque.produto', verbose_name='Produto Vinculado')),
            ],
            options={
                'verbose_name': 'Item da Nota de Entrada',
                'verbose_name_plural': 'Itens da Nota de Entrada',
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=20, verbose_name='Número da NF')),
                ('serie', models.CharField(default='1', max_length=5, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, help_text='44 dígitos da chave de acesso da NF-e', max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('natureza_operacao', models.CharField(blank=True, default='COMPRA PARA REVENDA', max_length=100, verbose_name='Natureza da Operação')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('data_conferencia', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conferência')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor dos Produtos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Seguro')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Desconto')),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Outras Despesas')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do IPI')),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor ICMS ST')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total da NF')),
                ('tipo_entrada', models.CharField(choices=[('M', 'Manual'), ('X', 'XML'), ('A', 'Automático (API)')], default='M', max_length=1, verbose_name='Tipo de Entrada')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Em Conferência'), ('C', 'Conferida'), ('F', 'Finalizada'), ('X', 'Cancelada')], default='P', max_length=1, verbose_name='Status')),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='nfe_entrada/%Y/%m/', verbose_name='Arquivo XML')),
                ('atualizar_preco_custo', models.BooleanField(default=True, help_text='Atualiza o preço de custo dos produtos ao finalizar', verbose_name='Atualizar Preço de Custo')),
                ('atualizar_preco_venda', models.BooleanField(default=False, help_text='Recalcula o preço de venda baseado na margem ao finalizar', verbose_name='Recalcular Preço de Venda')),
                ('margem_padrao', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Margem de lucro para recalcular preço de venda', max_digits=5, verbose_name='Margem Padrão (%)')),
                ('ratear_frete', models.BooleanField(default=True, help_text='Inclui o frete proporcional no custo de cada item', verbose_name='Ratear Frete no Custo')),
                ('atualizar_cotacao', models.BooleanField(default=True, help_text='Cria/atualiza cotação do fornecedor com os preços da NF', verbose_name='Atualizar Cotação do Fornecedor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrada', to='estoque.fornecedor', verbose_name='Fornecedor')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro')),
                ('usuario_conferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Conferência')),
                ('usuario_finalizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Finalização')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'ordering': ['-data_entrada', '-created_at'],
                'unique_together': {('numero_nf', 'serie', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='LogEntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Nota Criada'), ('IMPORTAR_XML', 'XML Importado'), ('VINCULAR', 'Produto Vinculado'), ('DESVINCULAR', 'Produto Desvinculado'), ('CONFERIR', 'Item Conferido'), ('CADASTRAR_PRODUTO', 'Produto Cadastrado'), ('FINALIZAR', 'Entrada Finalizada'), ('CANCELAR', 'Entrada Cancelada'), ('ATUALIZAR_ESTOQUE', 'Estoque Atualizado'), ('ATUALIZAR_PRECO', 'Preço Atualizado'), ('ATUALIZAR_COTACAO', 'Cotação Atualizada')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_json', models.JSONField(blank=True, null=True, verbose_name='Dados Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.itemnotaentrada', verbose_name='Item')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='compras.notafiscalentrada', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Log de Entrada',
                'verbose_name_plural': 'Logs de Entrada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itemnotaentrada',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.notafiscalentrada', verbose_name='Nota Fiscal'),
        ),
    ]
